In [1]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

df = pd.read_csv('C:/Users/Bolurin Sunday/Downloads/Data_for_UCI_named.csv')
df

,tau1,tau2,tau3,tau4,p1,p2,p3,p4,g1,g2,g3,g4,stab,stabf
0,2.959060,3.079885,8.381025,9.780754,3.763085,-0.782604,-1.257395,-1.723086,0.650456,0.859578,0.887445,0.958034,0.055347,unstable
1,9.304097,4.902524,3.047541,1.369357,5.067812,-1.940058,-1.872742,-1.255012,0.413441,0.862414,0.562139,0.781760,-0.005957,stable
2,8.971707,8.848428,3.046479,1.214518,3.405158,-1.207456,-1.277210,-0.920492,0.163041,0.766689,0.839444,0.109853,0.003471,unstable
3,0.716415,7.669600,4.486641,2.340563,3.963791,-1.027473,-1.938944,-0.997374,0.446209,0.976744,0.929381,0.362718,0.028871,unstable
4,3.134112,7.608772,4.943759,9.857573,3.525811,-1.125531,-1.845975,-0.554305,0.797110,0.455450,0.656947,0.820923,0.049860,unstable
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2.930406,9.487627,2.376523,6.187797,3.343416,-0.658054,-1.449106,-1.236256,0.601709,0.779642,0.813512,0.608385,0.023892,unstable
9996,3.392299,1.274827,2.954947,6.894759,4.349512,-1.663661,-0.952437,-1.733414,0.502079,0.567242,0.285880,0.366120,-0.025803,stable
9997,2.364034,2.842030,8.776391,1.008906,4.299976,-1.380719,-0.943884,-1.975373,0.487838,0.986505,0.149286,0.145984,-0.031810,stable
9998,9.631511,3.994398,2.757071,7.821347,2.514755,-0.966330,-0.649915,-0.898510,0.365246,0.587558,0.889118,0.818391,0.037789,unstable
9999,6.530527,6.781790,4.349695,8.673138,3.492807,-1.390285,-1.532193,-0.570329,0.073056,0.505441,0.378761,0.942631,0.045263,unstable

In [2]:
df.isnull().sum()

tau1     0
tau2     0
tau3     0
tau4     0
p1       0
p2       0
p3       0
p4       0
g1       0
g2       0
g3       0
g4       0
stab     0
stabf    0
dtype: int64

In [3]:
#Assigning independent and dependent variables from dataset

x = df.drop(columns= ['stab','stabf'])
y = df['stabf']
y.value_counts()

unstable    6380
stable      3620
Name: stabf, dtype: int64

In [4]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df.stabf = encoder.fit_transform(df.stabf)
df

,tau1,tau2,tau3,tau4,p1,p2,p3,p4,g1,g2,g3,g4,stab,stabf
0,2.959060,3.079885,8.381025,9.780754,3.763085,-0.782604,-1.257395,-1.723086,0.650456,0.859578,0.887445,0.958034,0.055347,1
1,9.304097,4.902524,3.047541,1.369357,5.067812,-1.940058,-1.872742,-1.255012,0.413441,0.862414,0.562139,0.781760,-0.005957,0
2,8.971707,8.848428,3.046479,1.214518,3.405158,-1.207456,-1.277210,-0.920492,0.163041,0.766689,0.839444,0.109853,0.003471,1
3,0.716415,7.669600,4.486641,2.340563,3.963791,-1.027473,-1.938944,-0.997374,0.446209,0.976744,0.929381,0.362718,0.028871,1
4,3.134112,7.608772,4.943759,9.857573,3.525811,-1.125531,-1.845975,-0.554305,0.797110,0.455450,0.656947,0.820923,0.049860,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2.930406,9.487627,2.376523,6.187797,3.343416,-0.658054,-1.449106,-1.236256,0.601709,0.779642,0.813512,0.608385,0.023892,1
9996,3.392299,1.274827,2.954947,6.894759,4.349512,-1.663661,-0.952437,-1.733414,0.502079,0.567242,0.285880,0.366120,-0.025803,0
9997,2.364034,2.842030,8.776391,1.008906,4.299976,-1.380719,-0.943884,-1.975373,0.487838,0.986505,0.149286,0.145984,-0.031810,0
9998,9.631511,3.994398,2.757071,7.821347,2.514755,-0.966330,-0.649915,-0.898510,0.365246,0.587558,0.889118,0.818391,0.037789,1
9999,6.530527,6.781790,4.349695,8.673138,3.492807,-1.390285,-1.532193,-0.570329,0.073056,0.505441,0.378761,0.942631,0.045263,1

In [5]:
#Training a dataset

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state = 1, test_size=0.2 )
x_test.head()

,tau1,tau2,tau3,tau4,p1,p2,p3,p4,g1,g2,g3,g4
9953,6.877876,4.113820,9.356768,8.299753,4.056779,-1.897470,-1.590581,-0.568728,0.276567,0.845536,0.112440,0.822562
3850,5.802841,6.271371,4.731540,3.819867,3.579569,-1.709480,-1.067511,-0.802579,0.077527,0.416478,0.912846,0.861306
4962,2.286998,4.385142,2.830232,5.293880,3.035814,-1.202764,-0.902011,-0.931039,0.924216,0.130186,0.703887,0.063811
3886,5.019920,2.209962,6.266080,0.578901,4.322584,-1.960207,-1.074561,-1.287815,0.546910,0.065992,0.427349,0.814648
5437,7.646145,9.187896,5.484219,9.934313,3.634226,-1.254541,-1.335366,-1.044319,0.561528,0.121611,0.787318,0.300314

In [6]:
print(y_train)

2694    unstable
5140    unstable
2568    unstable
3671    unstable
7427    unstable
          ...
2895      stable
7813      stable
905     unstable
5192    unstable
235       stable
Name: stabf, Length: 8000, dtype: object

In [7]:
mapping = {'stable': 1, 'unstable': 0}

# Replace the labels with their integer values using the mapping
df['stabf'] = df['stabf'].replace(mapping)

In [8]:
df

,tau1,tau2,tau3,tau4,p1,p2,p3,p4,g1,g2,g3,g4,stab,stabf
0,2.959060,3.079885,8.381025,9.780754,3.763085,-0.782604,-1.257395,-1.723086,0.650456,0.859578,0.887445,0.958034,0.055347,1
1,9.304097,4.902524,3.047541,1.369357,5.067812,-1.940058,-1.872742,-1.255012,0.413441,0.862414,0.562139,0.781760,-0.005957,0
2,8.971707,8.848428,3.046479,1.214518,3.405158,-1.207456,-1.277210,-0.920492,0.163041,0.766689,0.839444,0.109853,0.003471,1
3,0.716415,7.669600,4.486641,2.340563,3.963791,-1.027473,-1.938944,-0.997374,0.446209,0.976744,0.929381,0.362718,0.028871,1
4,3.134112,7.608772,4.943759,9.857573,3.525811,-1.125531,-1.845975,-0.554305,0.797110,0.455450,0.656947,0.820923,0.049860,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2.930406,9.487627,2.376523,6.187797,3.343416,-0.658054,-1.449106,-1.236256,0.601709,0.779642,0.813512,0.608385,0.023892,1
9996,3.392299,1.274827,2.954947,6.894759,4.349512,-1.663661,-0.952437,-1.733414,0.502079,0.567242,0.285880,0.366120,-0.025803,0
9997,2.364034,2.842030,8.776391,1.008906,4.299976,-1.380719,-0.943884,-1.975373,0.487838,0.986505,0.149286,0.145984,-0.031810,0
9998,9.631511,3.994398,2.757071,7.821347,2.514755,-0.966330,-0.649915,-0.898510,0.365246,0.587558,0.889118,0.818391,0.037789,1
9999,6.530527,6.781790,4.349695,8.673138,3.492807,-1.390285,-1.532193,-0.570329,0.073056,0.505441,0.378761,0.942631,0.045263,1

In [9]:
y_test.value_counts()
#There is an imbalance in the Dataset but we would work with them

unstable    1288
stable       712
Name: stabf, dtype: int64

In [10]:
x_test.value_counts()

tau1      tau2      tau3      tau4      p1        p2         p3         p4         g1        g2        g3        g4
0.515325  3.118991  4.034714  2.462564  4.374320  -1.118386  -1.373946  -1.881988  0.329011  0.960559  0.387731  0.502615    1
6.854473  0.932077  9.460633  6.051486  5.026656  -1.478129  -1.972752  -1.575775  0.338714  0.850080  0.808050  0.405710    1
6.909506  7.120376  3.301456  0.689737  2.815229  -0.787994  -1.417924  -0.609311  0.309715  0.534640  0.573991  0.564430    1
6.905367  5.960731  2.059017  0.592501  5.156702  -1.994250  -1.461413  -1.701039  0.866999  0.848552  0.089217  0.268193    1
6.903879  6.526275  2.133992  8.280049  4.536211  -1.945277  -1.764000  -0.826933  0.537797  0.617945  0.518107  0.784197    1
                                                                                                                            ..
3.630639  9.685668  1.145280  1.163448  3.517932  -1.222356  -1.340383  -0.955193  0.755650  0.998879  0.886236  0.390442    1
3.625925  3.303132  6.691957  9.852377  4.277447  -1.212106  -1.938179  -1.127162  0.369874  0.093810  0.296905  0.332527    1
3.615214  5.139669  7.530940  5.333233  3.447486  -1.428900  -1.279569  -0.739017  0.605538  0.855225  0.402997  0.457658    1
3.613646  6.292996  9.247772  0.897856  2.659731  -1.403790  -0.755004  -0.500937  0.945953  0.908675  0.195912  0.919317    1
9.993961  5.657540  9.383102  9.390915  3.228442  -1.286353  -0.910507  -1.031581  0.941401  0.271721  0.103172  0.377673    1
Length: 2000, dtype: int64

In [11]:
y_train.value_counts()

unstable    5092
stable      2908
Name: stabf, dtype: int64

In [12]:
x_train.value_counts()

tau1      tau2      tau3      tau4      p1        p2         p3         p4         g1        g2        g3        g4
0.500793  6.734360  5.284357  5.797771  3.387591  -0.752656  -0.972783  -1.662152  0.802707  0.204237  0.642260  0.513210    1
6.818537  9.247272  6.467968  1.791262  2.382490  -0.800627  -0.869578  -0.712285  0.544314  0.727335  0.835718  0.846119    1
6.834973  2.009239  1.745053  3.232995  2.727052  -0.577740  -1.247042  -0.902269  0.086041  0.202660  0.357411  0.848714    1
6.833746  8.847534  5.509003  6.320948  4.367438  -1.703936  -1.280371  -1.383131  0.709491  0.430811  0.583490  0.313310    1
6.832938  8.103769  9.659373  1.107526  4.748096  -0.896783  -1.972358  -1.878956  0.539333  0.731171  0.466057  0.603674    1
                                                                                                                            ..
3.663306  3.777186  5.392658  0.902859  3.375034  -1.151822  -1.148057  -1.075154  0.272599  0.856673  0.820077  0.677774    1
3.659313  1.991381  1.637647  1.569817  3.292358  -1.237096  -0.893677  -1.161585  0.284699  0.797662  0.782697  0.307094    1
3.658601  3.823051  3.382791  2.025699  3.589800  -1.499432  -0.517879  -1.572490  0.767596  0.188279  0.154670  0.257087    1
3.656944  8.636556  6.177594  4.499886  4.082783  -1.450646  -1.068126  -1.564011  0.244680  0.645080  0.377655  0.665789    1
9.999469  5.677620  8.002448  7.360514  3.280473  -0.870700  -0.707238  -1.702536  0.584174  0.296674  0.710548  0.233335    1
Length: 8000, dtype: int64

In [13]:
#Scaling Train Set

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaled_x_train = scaler.fit_transform(x_train)
scaled_x_train = DataFrame(scaled_x_train,columns = x_train.columns)
scaled_x_test = scaler.transform(x_test)
scaled_x_test = DataFrame(scaled_x_test, columns = x_test.columns)
scaled_x_train.head()

,tau1,tau2,tau3,tau4,p1,p2,p3,p4,g1,g2,g3,g4
0,0.367327,-0.986042,0.650447,1.547527,-0.291490,0.061535,1.293862,-0.845074,0.160918,0.339859,0.585568,0.492239
1,-0.064659,0.089437,1.035079,-1.641494,0.619865,-0.067235,-1.502925,0.486613,-0.293143,-1.558488,1.429649,-1.443521
2,-1.467850,1.298418,-0.502536,1.166046,-0.180521,0.490603,0.682560,-0.855302,1.399350,1.451534,-1.045743,0.492489
3,0.820081,0.529920,1.299657,-1.141975,-0.812854,-0.763632,1.521579,0.658780,-0.958319,1.361958,1.604140,0.275303
4,0.665424,-1.425627,0.312300,0.919137,-1.614296,0.760315,1.422019,0.639243,1.676895,0.695660,1.137504,-1.312575

In [14]:
#Random Forest

from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(random_state =1)
classifier.fit(scaled_x_train,y_train)
forest_pred = classifier.predict(scaled_x_test)

In [15]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test,forest_pred)
round(accuracy,4)

0.929

In [16]:
#Extra Trees Classifier

from sklearn.ensemble import ExtraTreesClassifier
tree_classifier = ExtraTreesClassifier(random_state = 1)
tree_classifier.fit(scaled_x_train,y_train)
tree_pred = tree_classifier.predict(scaled_x_test)

accuracy = accuracy_score(y_test,tree_pred)
round(accuracy,4)

0.928

In [17]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df.stabf = encoder.fit_transform(df.stabf)

In [18]:
#Light GBM

from lightgbm import LGBMClassifier
lgbm = LGBMClassifier(random_state=1)
lgbm.fit(scaled_x_train,y_train)
lgbm_pred = lgbm.predict(scaled_x_test)

accuracy = accuracy_score(y_test,lgbm_pred)
round(accuracy,4)

0.9395

In [19]:
!pip install --upgrade pip

Requirement already satisfied: pip in c:\users\bolurin sunday\anaconda3\lib\site-packages (23.0.1)

In [20]:
!pip install lightgbm

Requirement already satisfied: lightgbm in c:\users\bolurin sunday\anaconda3\lib\site-packages (3.3.5)
Requirement already satisfied: scipy in c:\users\bolurin sunday\anaconda3\lib\site-packages (from lightgbm) (1.9.1)
Requirement already satisfied: scikit-learn!=0.22.0 in c:\users\bolurin sunday\anaconda3\lib\site-packages (from lightgbm) (1.0.2)
Requirement already satisfied: wheel in c:\users\bolurin sunday\anaconda3\lib\site-packages (from lightgbm) (0.37.1)
Requirement already satisfied: numpy in c:\users\bolurin sunday\anaconda3\lib\site-packages (from lightgbm) (1.21.5)
Requirement already satisfied: joblib>=0.11 in c:\users\bolurin sunday\anaconda3\lib\site-packages (from scikit-learn!=0.22.0->lightgbm) (1.1.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\bolurin sunday\anaconda3\lib\site-packages (from scikit-learn!=0.22.0->lightgbm) (2.2.0)

In [21]:
#Tunning Parameters

n_estimators = [50,100,300,500,1000] #number of estimators
min_samples_split = [2,3,5,7,9] #minimum number of splits
min_samples_leaf = [1,2,4,6,8] #minimum number of samples for leaf node
max_features = ['auto','sqrt','log2',None] #the number of features to consider when looking for the best split
hyperparameter_grid = {'n_estimators':n_estimators,
                       'min_samples_leaf':min_samples_leaf,
                       'min_samples_split':min_samples_split,
                       'max_features':max_features}

In [22]:
#Randomized Search

from sklearn.model_selection import RandomizedSearchCV
     
random_search = RandomizedSearchCV(estimator = tree_classifier, param_distributions=hyperparameter_grid,random_state=1)
random_search = random_search.fit(scaled_x_train,y_train)
     
random_search.best_params_

{'n_estimators': 1000,
 'min_samples_split': 2,
 'min_samples_leaf': 8,
 'max_features': None}

In [23]:
#Training ExtraTreesClassifier with new Hyperparameter

new_classifier = ExtraTreesClassifier(random_state=1,n_estimators = 1000, min_samples_leaf= 8,max_features=None, min_samples_split=2)
new_classifier.fit(scaled_x_train,y_train)
new_pred = new_classifier.predict(scaled_x_test)
     
accuracy = accuracy_score(y_test,new_pred)
round(accuracy,4) #its value reduced

0.927

In [24]:
#Feature Importance

importance = random_search.best_estimator_.feature_importances_
importance

array([0.13723975, 0.1405075 , 0.13468029, 0.13541676, 0.00368342,
       0.00533686, 0.00542927, 0.00496249, 0.10256244, 0.10757765,
       0.11306268, 0.10954089])

In [25]:
sorted(zip(importance,x),reverse = True)

[(0.14050750384993677, 'tau2'),
 (0.13723974766109256, 'tau1'),
 (0.1354167630909727, 'tau4'),
 (0.13468028520386593, 'tau3'),
 (0.11306267999167334, 'g3'),
 (0.10954089174337298, 'g4'),
 (0.10757764577478764, 'g2'),
 (0.10256244080927947, 'g1'),
 (0.005429268421191957, 'p3'),
 (0.005336864710946151, 'p2'),
 (0.004962486591192238, 'p4'),
 (0.003683422151688322, 'p1')]

In [26]:
#XG-Boost

from xgboost import XGBClassifier
boost = XGBClassifier(random_state=1)
boost.fit(scaled_x_train, y_train)
boost_pred = boost.predict(scaled_x_test)
 
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test,boost_pred)
round(accuracy, 4)

ValueError: Invalid classes inferred from unique values of `y`.  Expected: [0 1], got ['stable' 'unstable']